begin;

create table if not exists "Candidates_shadow" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lever_id text unique,
  name text,
  email text,
  phone text,
  last_four text,
  magic_token text,
  current_stage text,
  position text,
  application_phone text,
  next_interview timestamptz,
  stage_updated timestamptz default now(),
  person_key text,
  portal_access boolean,
  identity_confidence smallint,
  portal_stage text,
  portal_stage_order smallint,
  offer_access boolean,
  portal_stage_terminal boolean,
  application_last_name_norm text,
  archived boolean default false,
  offer_letter_key text,
  offer_letter_signed_url text,
  hiring_manager text,
  recruiter text,
  offer_status text,
  offer_file_path text,
  archive_reason text,
  recruiter_email text,
  offer_uploaded_at timestamptz,
  application_last_name text
);

create index if not exists idx_candidates_shadow_person_key on "Candidates_shadow"(person_key);
create index if not exists idx_candidates_shadow_stage_updated on "Candidates_shadow"(stage_updated desc);

comment on table "Candidates_shadow" is 'Phase 1 compatibility read model for parity. No portal cutover until identity/token fields are fully materialized and validated.';

commit;
